use_frameworks!

platform :ios, '12.0'

target 'AppierAdsApplovinMediation_Example' do
  pod 'AppierAdsApplovinMediation', :path => '../'

  target 'AppierAdsApplovinMediation_Tests' do
    inherit! :search_paths

    
  end
end
